spring: ## General Config  
   application.name: sofia2-example-metrics
   boot.admin: #Spring Boot Admin Config    
      url: http://localhost:18090
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: $spring.boot.admin.password}

## LOGGING CONF
logging:
   level:
      org.springframework: INFO
      com.indra: INFO


 