global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  # The auth token for Hipchat.
  hipchat_auth_token: '1234556789'
  # Alternative host for Hipchat.
  hipchat_api_url: 'https://hipchat.foobar.org/'

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  repeat_interval: 1m
  receiver: team-X-mails
  routes:
  - match:
      action: up
    receiver: 'scale-up'
  - match:
      action: down
    receiver: 'scale-down'
receivers:
- name: 'scale-up'
  webhook_configs:
  - url: http://sofia2-dockerstack.westeurope.cloudapp.azure.com/v1-webhooks/endpoint?key=422e1mpqlcqzhslVhZkm4rlKVyVxUx0P4QfI1snt&projectId=1a5
    send_resolved: true
- name: 'scale-down'
  webhook_configs:
  - url: http://sofia2-dockerstack.westeurope.cloudapp.azure.com/v1-webhooks/endpoint?key=nMcvMUn0gJl3fwkfQ7MeEHVUDeSVpIVojCeP5cXM&projectId=1a5
    send_resolved: true
- name: 'team-X-mails'                                                                                                                        
  email_configs:                                                                                                                              
  - to: 'team-X+alerts@example.org'    