# Gmail Config for SMTP
spring:
   mail:
      host: smtp.gmail.com
      port: 587
      username: correodepruebassofia2@gmail.com
      password: sofia22018
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.timeout: 5000
      properties.mail.smtp.connectiontimeout: 5000
      properties.mail.smtp.writetimeout: 5000