#Integration Resources
sofia2:
  module:
    integration:
      iot-broker:
        base:
          url: http://iotbrokerservice:8081/
        advice:
          url: http://iotbrokerservice:8081/iotbroker/advice
      scripting-engine:
        base:
          url: 
        advice:
          url: 
      node-red:
        base:
          url: http://flowengineservice:8082/sofia2/flowengine/admin
        advice:
          url: http://flowengineservice:5050/
      router-standalone:
        base:
          url: http://localhost:19100/
        advice:
          url: http://localhost:19100/router/router/advice/
        management:
          url: http://localhost:19100/router/management/
        router:
          url: http://localhost:19100/router/router/
        hawtio:
          url: http://localhost:19100/hawtio/index.html
        swagger-ui:
          url: http://${SERVER_NAME}/router/swagger-ui.html
      api-manager:
        base:
          url: http://apimanagerservice:19090/api-manager/
        api:
          url: http://apimanagerservice:19090/api-manager/server/api/
        swagger-ui:
          url: http://${SERVER_NAME}/api-manager/services/management/api-docs?url=
        swagger-ui-management:
          url: http://${SERVER_NAME}/api-manager/services/management/api-docs?url=/services/management/swagger.json
        swagger-json:
          url: http://${SERVER_NAME}/api-manager/services/management/swagger/
          