## SERVER CONF
server:
   port: 18081
   contextPath: systemconfig-init
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
spring:
   ## GENERAL CONFIG
   application.name: systemconfig-init
   ## JPA Config
   datasource:
      url: jdbc:mysql://localhost:3306/sofia2_s4c?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password:  
      # Number of ms to wait before throwing an exception if no connection is available.
      tomcat.max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      tomcat.max-active: 50
      # Validate the connection before borrowing it from the pool.
      tomcat.test-on-borrow: true
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: create
            
## LOGGING CONF
logging:
   level:
      org.springframework: INFO
      com.example.boot.thymeleaf: INFO
      com.indra: DEBUG
      org.hibernate: INFO


 