version: "2.1"

services:
  controlpanelinstance:
    image: sofia2/controlpanel:${IMAGETAG}
    container_name: controlpanelservice    
    networks:
      - dockerdata_datanetwork
    ports:
     - "8091:18080"
    external_links:
     - configdb
     - schedulerdb
     - realtimedb    
  iotbrokerinstance:
    image: sofia2/iotbroker:${IMAGETAG}
    container_name: iotbrokerservice    
    networks:
      - dockerdata_datanetwork
    ports:
     - "8092:8081"
    external_links:
     - configdb
     - schedulerdb
     - realtimedb      
networks:
  dockerdata_datanetwork:
    external: true
